---
title: "Interfaz Pronostico Estacional"
output:
       flexdashboard::flex_dashboard:
         orientation: rows
         vertical_layout: scroll
         theme: bootstrap
runtime: shiny
# output: 
#       html_document: 
#           code_folding: hide
# runtime: shiny
#output: pdf_document
#runtime: shiny
---
```{r setup, include=FALSE}

library(flexdashboard)
library(knitr)
library(plotly)
library(plyr)
library(tidyverse)
library(stats)
library(here)
library(shiny)
library(shinyjs)
```

```{r global, include=FALSE}

source('./Script_externo.R')

deciles_nombre = c('0-10','10-20','20-30',
           '30-40','40-50','50-60',
           '60-70','70-80','80-90','90-100')

deciles_Arenal = c('91','148','223','274','326','361','404','449','502','729')
deciles_Penas = c('119','209','303','379','446','518','562','621','721','1083')
deciles_Toro1 = c('77','147','220','272','309','355','393','450','531','1283')
deciles_Cariblanco = c('101','200','292','370','411','469','519','583','735','1583')
deciles_RioMacho = c('90','135','193','251','305','342','385','427','473','817')
deciles_Cachi = c('75','115','164','221','266','310','342','374','422','602')
deciles_Angostura = c('111','171','226','283','321','367','404','444','503','758')
deciles_Reventazon = c('123','198','249','270','293','328','364','415','484','849')
deciles_Ventanas = c('16','34','56','101','176','225','274','335','413','721')
deciles_Pirris = c('14','28','49','93','152','221','265','319','389','729')


month <- as.integer(tail(data_model,1)['Mes'])

if (month==12) {
  month2 <- 1
} else {
    month2 <- as.integer(month)+1
  }

```

Column {.sidebar column-width=200}
=========================================================================

```{r}

selectInput('estacion', 'Cuenca', colnames(redn))

tex <- reactive(round(promedios[[input$estacion]][month2,]))
dec <- reactive(t(decil_val[,input$estacion]))



```

Ensamble
=========================================================================

Row {data-height=650}
-------------------------------------

### 

```{r}


renderPlotly(plot_ly(data.frame(deciles = deciles_nombre,valor = redn[,input$estacion] %>% unlist() %>% unname()),
             x = ~deciles_nombre,
             y = ~redn[,input$estacion] %>% unlist() %>% unname(),
             type = 'bar',
             name = 'Viridis',
             color = 'Jet',
             text=decil_val[,input$estacion],
             textposition = 'auto', textfont=list(size=10, color="black")) %>%
  layout(title = 'Resultados de Ensamble',
         yaxis = list(title = 'Probabilidad'),
         xaxis = list(title = 'Decil')))
```

Row {data-height=120}
-------------------------------------
### Información deciles
```{r}

renderTable(dec(),spacing = "l")

```



Row {data-height=150}
-------------------------------------
### Ultimo Mes Medido

```{r}

valueBox(month, icon = "fa-calendar-check", color ="light-blue")

```

### Promedio Lluvia Mensual
```{r}

renderValueBox(valueBox(tex(), icon = "fa-balance-scale-right", color = "light-blue"))
```

### Mes Pronosticado
```{r}

valueBox(month2, icon = "fa-arrow-alt-circle-right",color = "light-blue")

```




Modelos
=========================================================================

Row {data-height=550}
------------------------------------------------

###

```{r}


renderPlotly(ggplotly(ggplot(data = data_modelos[[input$estacion]] %>% mutate(obs = 1:10) %>%  gather('modelo', 'value', -c(obs)), aes(x= obs,y = value, group = modelo))+
   geom_line(aes(linetype=modelo,color=modelo))+
   geom_point(aes(shape=modelo,color = modelo))+
   scale_x_continuous(breaks = 1:10,labels=deciles_nombre)+
   xlab('Decil')+
   ylab('Probabilidad') ))


```

Row {data-height=650}
--------------------------------------------------------------------------
### Ultimo Mes Medido

```{r}
valueBox(month, icon = "fa-calendar-check", color = "light-blue")

```

### Promedio Lluvia Mensual
```{r}
#tex <- reactive(round(promedios[[input$estacion]][month,]))
renderValueBox(valueBox(tex(), icon = "fa-balance-scale-right", color = "light-blue"))
```

### Mes Pronosticado
```{r}
valueBox(month2, icon = "fa-arrow-alt-circle-right", color = "light-blue")
```

Conjunto
=========================================================================

Row {data-height=650}
-------------------------------------

### 

```{r}


p1<-plot_ly(data.frame(deciles = deciles_Reventazon,valor = redn[,'Reventazon'] %>% unlist() %>% unname()),
             x = ~as.numeric(deciles_Reventazon),
             y = ~redn[,'Reventazon'] %>% unlist() %>% unname(),
             type = 'bar',
             name = 'Reventazon',
             marker_color = 'Jet'
            ) %>% 
    layout(title = "Reventazon", 
           xaxis = list(type = "category",
                        categoryorder = "total ascending"
                        ))
  

  p2<-plot_ly(data.frame(deciles = deciles_Penas,valor = redn[,'Penas'] %>% unlist() %>% unname()),
             x = ~as.numeric(deciles_Penas),
             y = ~redn[,'Penas'] %>% unlist() %>% unname(),
             type = 'bar',
             name = 'Penas',
             marker_color = 'black') %>% 
    layout(title = "Pe?as Blancas", 
           xaxis = list(type = "category",
                        categoryorder = "total ascending"
                        ))
  
  
  
  
  
  p3<-plot_ly(data.frame(deciles = deciles_Arenal,valor = redn[,'Arenal'] %>% unlist() %>% unname()),
             x = ~as.numeric(deciles_Arenal),
             y = ~redn[,'Arenal'] %>% unlist() %>% unname(),
             type = 'bar',
             name = 'Arenal',
             marker_color = 'azure') %>% 
    layout(title = "Arenal", 
           xaxis = list(type = "category",
                        categoryorder = "total ascending"
                        ))
  
  
  p4<-plot_ly(data.frame(deciles = deciles_Angostura,valor = redn[,'Angostura'] %>% unlist() %>% unname()),
             x = ~as.numeric(deciles_Angostura),
             y = ~redn[,'Angostura'] %>% unlist() %>% unname(),
             type = 'bar',
             name = 'Angostura',
             marker_color = 'cornsilk') %>% 
    layout(title = "Angostura", 
           xaxis = list(type = "category",
                        categoryorder = "total ascending"
                        ))
  
  
  p5<-plot_ly(data.frame(deciles = deciles_Pirris,valor = redn[,'Pirris'] %>% unlist() %>% unname()),
             x = ~as.numeric(deciles_Pirris),
             y = ~redn[,'Pirris'] %>% unlist() %>% unname(),
             type = 'bar',
             name = 'Pirris',
             marker_color = 'lavender') %>% 
    layout(title = "Pirris", 
           xaxis = list(type = "category",
                        categoryorder = "total ascending"
                        ))
  
  
  p6<-plot_ly(data.frame(deciles = deciles_Cariblanco,valor = redn[,'Cariblanco'] %>% unlist() %>% unname()),
             x = ~as.numeric(deciles_Cariblanco),
             y = ~redn[,'Cariblanco'] %>% unlist() %>% unname(),
             type = 'bar',
             name = 'Cariblanco',
             marker_color = 'gainsboro') %>% 
    layout(title = "Cariblanco", 
           xaxis = list(type = "category",
                        categoryorder = "total ascending"
                        ))
  
  p7<-plot_ly(data.frame(deciles = deciles_Cachi,valor = redn[,'Cachi'] %>% unlist() %>% unname()),
             x = ~as.numeric(deciles_Cachi),
             y = ~redn[,'Cachi'] %>% unlist() %>% unname(),
             type = 'bar',
             name = 'Cachi',
             marker_color = 'burlywood') %>% 
    layout(title = "Cachi", 
           xaxis = list(type = "category",
                        categoryorder = "total ascending"
                        ))
  
  
  p8<-plot_ly(data.frame(deciles = deciles_Ventanas,valor = redn[,'Ventanas'] %>% unlist() %>% unname()),
             x = ~as.numeric(deciles_Ventanas),
             y = ~redn[,'Ventanas'] %>% unlist() %>% unname(),
             type = 'bar',
             name = 'Ventanas',
             marker_color = 'aqua') %>% 
    layout(title = "Ventanas", 
           xaxis = list(type = "category",
                        categoryorder = "total ascending"
                        ))
  
  
  p9<-plot_ly(data.frame(deciles = deciles_Toro1,valor = redn[,'Toro1'] %>% unlist() %>% unname()),
             x = ~as.numeric(deciles_Toro1),
             y = ~redn[,'Toro1'] %>% unlist() %>% unname(),
             type = 'bar',
             name = 'Toro1',
             marker_color = 'springgreen') %>% 
    layout(title = "Toro1", 
           xaxis = list(type = "category",
                        categoryorder = "total ascending"
                        ))
  
  
  p10<-plot_ly(data.frame(deciles = deciles_RioMacho,valor = redn[,'RioMacho'] %>% unlist() %>% unname()),
             x = ~as.numeric(deciles_RioMacho),
             y = ~redn[,'RioMacho'] %>% unlist() %>% unname(),
             type = 'bar',
             name = 'RioMacho',
             marker_color = 'thistle') %>% 
    layout(title = "RioMacho", 
           xaxis = list(type = "category",
                        categoryorder = "total ascending"
                        ))
  
  
  renderPlotly(subplot(p1,p2,p3,p4,p5,p6,p7,p8,p9,p10,nrows = 5,margin = 0.04))
```




